# **Computational Drug Discovery [Part 1] Download Bioactivity Data**

## **ChEMBL Database**

The [*ChEMBL Database*](https://www.ebi.ac.uk/chembl/) is a database that contains curated bioactivity data of more than 2 million compounds. It is compiled from more than 76,000 documents, 1.2 million assays and the data spans 13,000 targets and 1,800 cells and 33,000 indications.
[Data as of March 25, 2020; ChEMBL version 26].

## **Installing libraries**

Install the ChEMBL web service package so that we can retrieve bioactivity data from the ChEMBL Database.

In [9]:
! pip install chembl_webresource_client

                                    canonical_smiles     pIC50
0  Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...  7.387216
1  Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...  6.522879
2  Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...  5.106793
3  Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...  6.769551
4  Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...  7.397940

## **Importing libraries**

In [10]:
# Import necessary libraries
import pandas as pd
from chembl_webresource_client.new_client import new_client

## **Search for Target protein**

### **Target search for keap1**

In [11]:
# Target search for nrf2_keap1
target = new_client.target
target_query = target.search('Keap1')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Keap1/Nrf2,17.0,False,CHEMBL3038498,"[{'accession': 'Q16236', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
1,[],Rattus norvegicus,KEAP1/NRF2,17.0,False,CHEMBL4296095,"[{'accession': 'O54968', 'component_descriptio...",PROTEIN COMPLEX,10116
2,[],Rattus norvegicus,Kelch-like ECH-associated protein 1,13.0,False,CHEMBL4523596,"[{'accession': 'P57790', 'component_descriptio...",SINGLE PROTEIN,10116
3,[],Mus musculus,Kelch-like ECH-associated protein 1,12.0,False,CHEMBL3562164,"[{'accession': 'Q9Z2X8', 'component_descriptio...",SINGLE PROTEIN,10090
4,[],Homo sapiens,Kelch-like ECH-associated protein 1,11.0,False,CHEMBL2069156,"[{'accession': 'Q14145', 'component_descriptio...",SINGLE PROTEIN,9606
5,[],Mus musculus,Protein cereblon/Kelch-like ECH-associated pro...,11.0,False,CHEMBL5465249,"[{'accession': 'Q9Z2X8', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,10090
6,[],Homo sapiens,Kelch-like ECH-associated protein 1/Bromodomai...,10.0,False,CHEMBL6193832,"[{'accession': 'O60885', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
7,[],Homo sapiens,Kelch-like ECH-associated protein 1/Microtubul...,9.0,False,CHEMBL4296122,"[{'accession': 'P10636', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
8,[],Homo sapiens,Sequestosome-1/Kelch-like ECH-associated prote...,8.0,False,CHEMBL4106129,"[{'accession': 'Q14145', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
9,[],Mus musculus,Kelch-like ECH-associated protein 1/Nuclear fa...,8.0,False,CHEMBL4296107,"[{'accession': 'Q60795', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,10090
10,[],Homo sapiens,Kelch-like ECH-associated protein 1/Microtubul...,8.0,False,CHEMBL4296123,"[{'accession': 'P10636', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
11,[],Homo sapiens,Kelch-like ECH-associated protein 1/Cyclin-dep...,7.0,False,CHEMBL6193838,"[{'accession': 'P50750', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606

In [12]:
selected_target = targets.target_chembl_id[4]
selected_target

'CHEMBL2069156'

Here, we will retrieve only bioactivity data for *coronavirus 3C-like proteinase* (CHEMBL3927) that are reported as IC$_{50}$ values in nM (nanomolar) unit.

In [13]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [14]:
df = pd.DataFrame.from_dict(res)

In [15]:
df.head(3)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,13378747,[],CHEMBL2406877,Displacement of MR121-Nrf2 from human N-termin...,B,None,None,BAO_0000190,...,Homo sapiens,Kelch-like ECH-associated protein 1,9606,None,None,IC50,uM,UO_0000065,None,2.7
1,None,None,13378748,[],CHEMBL2406877,Displacement of MR121-Nrf2 from human N-termin...,B,None,None,BAO_0000190,...,Homo sapiens,Kelch-like ECH-associated protein 1,9606,None,None,IC50,uM,UO_0000065,None,118.0
2,None,None,13378749,[],CHEMBL2406877,Displacement of MR121-Nrf2 from human N-termin...,B,None,None,BAO_0000190,...,Homo sapiens,Kelch-like ECH-associated protein 1,9606,None,None,IC50,nM,UO_0000065,None,33.0

In [16]:
df.standard_type.unique()

array(['IC50'], dtype=object)

Finally we will save the resulting bioactivity data to a CSV file **bioactivity_data.csv**.

In [17]:
df.to_csv('bioactivity_data.csv', index=False)

In [18]:
! head bioactivity_data.csv

action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,modality,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,,13378747,[],CHEMBL2406877,Displacement of MR121-Nrf2 from human N-terminal His-tagged Kelch-DC domain of Keap1 (321 to 609) expressed in Escherichia coli BL21 (DE3) after 40 mins by 2D-FIDA assay,B,,,BAO_0000190,BAO_0000019,assay format,COc1ccc(S(=O)(=O)Nc2ccc(NS(=O)(=O)c3ccc(OC)cc3)c3ccccc23)cc1,,,CHEMBL2401631,Bioorg Med Chem,2013,"{'bei': '11.17', 'le': '0.22', 'lle': '1.11', 'sei': '5.03'}",,CHEMBL2402207,,CHEMBL2402207,5.57,0,http://www.openphacts.org/units/Nanomolar,1905196,=,1,1,=,,IC50,nM,,2700.0,CHEMBL2069156,Homo sapiens,Kelch-like ECH-associated protein 1,9606,,,IC50,uM,UO_0000065,,2.7
,,13378748,[],CHEMBL2406877,Displacement of MR121-Nrf2 from human N-terminal His-tagged Kelch-DC domain of Keap1 (321 to 609) expressed in Escherichia coli BL21 (DE3) after 40 mins by 2D-FIDA assay,B,,,BAO_0000190,BAO_0000019,assay format,Cc1ccc(S(=O)(=O)c2cnc(SCC(=O)Nc3ccccc3C(F)(F)F)[nH]c2=O)c(C)c1,Outside typical range,"Values for this activity type are unusually large/small, so may not be accurate",CHEMBL2401631,Bioorg Med Chem,2013,,,CHEMBL2402206,,CHEMBL2402206,,0,http://www.openphacts.org/units/Nanomolar,1905195,=,1,1,=,,IC50,nM,,118000.0,CHEMBL2069156,Homo sapiens,Kelch-like ECH-associated protein 1,9606,,,IC50,uM,UO_0000065,,118.0
,,13378749,[],CHEMBL2406877,Displacement of MR121-Nrf2 from human N-terminal His-tagged Kelch-DC domain of Keap1 (321 to 609) expressed in Escherichia coli BL21 (DE3) after 40 mins by 2D-FIDA assay,B,,,BAO_0000190,BAO_0000019,assay format,CC(C)C[C@H](NC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](CCC(=O)O)NC(=O)CNC(=O)[C@@H](NC(=O)[C@H](CCC(=O)O)NC(=O)[C@H](CCC(=O)O)NC(=O)[C@H](CC(=O)O)NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CCC(N)=O)NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CCC(N)=O)NC(=O)[C@H](C)NC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](C)N)[C@@H](C)O)C(=O)O,,,CHEMBL2401631,Bioorg Med Chem,2013,"{'bei': '4.03', 'le': None, 'lle': None, 'sei': None}",,CHEMBL2402205,,CHEMBL2402205,7.48,0,http://www.openphacts.org/units/Nanomolar,1905194,=,1,1,=,,IC50,nM,,33.0,CHEMBL2069156,Homo sapiens,Kelch-like ECH-associated protein 1,9606,,,IC50,nM,UO_0000065,,33.0
,,15767053,[],CHEMBL3637038,Binding affinity to the Keap1 (321 to 609 residues) (unknown origin) expressed in Escherichia coli BL21 (DE3) cells by surface plasmon resonance assay,B,,,BAO_0000190,BAO_0000219,cell-based format,COc1ccc(S(=O)(=O)Nc2ccc(NS(=O)(=O)c3ccc(OC)cc3)c3ccccc23)cc1,,,CHEMBL3632561,Eur J Med Chem,2015,"{'bei': '11.57', 'le': '0.23', 'lle': '1.31', 'sei': '5.21'}",,CHEMBL2402207,,CHEMBL2402207,5.77,0,http://www.openphacts.org/units/Nanomolar,2509195,=,1,1,=,,IC50,nM,,1700.0,CHEMBL2069156,Homo sapiens,Kelch-like ECH-associated protein 1,9606,,,IC50,nM,UO_0000065,,1700.0
,,15767054,[],CHEMBL3637038,Binding affinity to the Keap1 (321 to 609 residues) (unknown origin) expressed in Escherichia coli BL21 (DE3) cells by surface plasmon resonance assay,B,,,BAO_0000190,BAO_0000219,cell-based format,COc1ccc(S(=O)(=O)N(CC(=O)O)c2ccc(N(CC(=O)O)S(=O)(=O)c3ccc(OC)cc3)c3ccccc23)cc1,,,CHEMBL3632561,Eur J Med Chem,2015,"{'bei': '12.53', 'le': '0.25', 'lle': '4.28', 'sei': '4.59'}",,CHEMBL3237245,,CHEMBL3237245,7.70,0,http://www.openphacts.org/units/Nanomolar,2509196,=,1,1,=,,IC50,nM,,20.0,CHEMBL2069156,Homo sapiens,Kelch-like ECH-associated protein 1,9606,,,IC50,nM,UO_0000065,,20.0
,Not Determined,15767055,[],CHEMBL3637038,Binding affinity to the Keap1 (321 to 609 residues) (unknown origin) expressed in Escherichia coli BL21 (DE3) cells by surface plasmon resonance assay,B,,,BAO_0000190,BAO_0000219,cell-based format,O=S(=O)(Nc1ccc(NS(=O)(=O)c2ccccc2)c2ccccc12)c1ccccc1,,,CHEMBL3632561,Eur J Med Chem,2015,,,CHEMBL2133303,,CHEMBL2133303,,0,,2509197,,1,0,,,IC50,,,,CHEMBL2069156,Homo sapiens,Kelch-like ECH-associated protein 1,9606,,,IC50,,,,
,,15767056,[],CHEMBL3637038,Binding affinity to the Keap1 (321 to 609 residues) (unknown origin) expressed in Escherichia coli BL21 (DE3) cells by surface plasmon resonance assay,B,,,BAO_0000190,BAO_0000219,cell-based format,COc1cccc(S(=O)(=O)Nc2ccc(NS(=O)(=O)c3cccc(OC)c3)c3ccccc23)c1,,,CHEMBL3632561,Eur J Med Chem,2015,"{'bei': '11.31', 'le': '0.23', 'lle': '1.18', 'sei': '5.09'}",,CHEMBL3632699,,CHEMBL3632699,5.64,0,http://www.openphacts.org/units/Nanomolar,2509198,=,1,1,=,,IC50,nM,,2300.0,CHEMBL2069156,Homo sapiens,Kelch-like ECH-associated protein 1,9606,,,IC50,nM,UO_0000065,,2300.0
,Not Determined,15767057,[],CHEMBL3637038,Binding affinity to the Keap1 (321 to 609 residues) (unknown origin) expressed in Escherichia coli BL21 (DE3) cells by surface plasmon resonance assay,B,,,BAO_0000190,BAO_0000219,cell-based format,O=S(=O)(Nc1ccc(NS(=O)(=O)c2ccc(Cl)cc2)c2ccccc12)c1ccc(Cl)cc1,,,CHEMBL3632561,Eur J Med Chem,2015,,,CHEMBL484276,,CHEMBL484276,,0,,2509199,,1,0,,,IC50,,,,CHEMBL2069156,Homo sapiens,Kelch-like ECH-associated protein 1,9606,,,IC50,,,,
,Not Determined,15767058,[],CHEMBL3637038,Binding affinity to the Keap1 (321 to 609 residues) (unknown origin) expressed in Escherichia coli BL21 (DE3) cells by surface plasmon resonance assay,B,,,BAO_0000190,BAO_0000219,cell-based format,O=C(O)c1cccc(S(=O)(=O)Nc2ccc(NS(=O)(=O)c3cccc(C(=O)O)c3)c3ccccc23)c1,,,CHEMBL3632561,Eur J Med Chem,2015,,,CHEMBL3632700,,CHEMBL3632700,,0,,2509200,,1,0,,,IC50,,,,CHEMBL2069156,Homo sapiens,Kelch-like ECH-associated protein 1,9606,,,IC50,,,,

## **Handling missing data**
If any compounds has missing value for the **standard_value** column then drop it

In [19]:
df2 = df[df.standard_value.notna()]
df2

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,13378747,[],CHEMBL2406877,Displacement of MR121-Nrf2 from human N-termin...,B,None,None,BAO_0000190,...,Homo sapiens,Kelch-like ECH-associated protein 1,9606,None,None,IC50,uM,UO_0000065,None,2.7
1,None,None,13378748,[],CHEMBL2406877,Displacement of MR121-Nrf2 from human N-termin...,B,None,None,BAO_0000190,...,Homo sapiens,Kelch-like ECH-associated protein 1,9606,None,None,IC50,uM,UO_0000065,None,118.0
2,None,None,13378749,[],CHEMBL2406877,Displacement of MR121-Nrf2 from human N-termin...,B,None,None,BAO_0000190,...,Homo sapiens,Kelch-like ECH-associated protein 1,9606,None,None,IC50,nM,UO_0000065,None,33.0
3,None,None,15767053,[],CHEMBL3637038,Binding affinity to the Keap1 (321 to 609 resi...,B,None,None,BAO_0000190,...,Homo sapiens,Kelch-like ECH-associated protein 1,9606,None,None,IC50,nM,UO_0000065,None,1700.0
4,None,None,15767054,[],CHEMBL3637038,Binding affinity to the Keap1 (321 to 609 resi...,B,None,None,BAO_0000190,...,Homo sapiens,Kelch-like ECH-associated protein 1,9606,None,None,IC50,nM,UO_0000065,None,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24992837,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5230555,Inhibition of human KEAP1 incubated for 60 min...,B,None,None,BAO_0000190,...,Homo sapiens,Kelch-like ECH-associated protein 1,9606,None,None,IC50,nM,UO_0000065,None,7.7
379,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24992838,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5230555,Inhibition of human KEAP1 incubated for 60 min...,B,None,None,BAO_0000190,...,Homo sapiens,Kelch-like ECH-associated protein 1,9606,None,None,IC50,uM,UO_0000065,None,1.4
380,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24992848,[],CHEMBL5230559,Inhibition of human KEAP1 by fluorescence pola...,B,None,None,BAO_0000190,...,Homo sapiens,Kelch-like ECH-associated protein 1,9606,None,None,IC50,nM,UO_0000065,None,31.0
381,None,None,26302310,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5701177,Inhibition of KEAP1 (unknown origin) incubated...,B,None,None,BAO_0000190,...,Homo sapiens,Kelch-like ECH-associated protein 1,9606,None,None,IC50,uM,UO_0000065,None,10.0
382,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29059451,[],CHEMBL6072894,Inhibition of Keap1 (unknown origin) by fluore...,B,None,None,BAO_0000190,...,Homo sapiens,Kelch-like ECH-associated protein 1,9606,None,None,IC50,nM,UO_0000065,None,230.0

Apparently, for this dataset there is no missing data. But we can use the above code cell for bioactivity data of other target protein.

## **Data pre-processing of the bioactivity data**

### **Labeling compounds as either being active, inactive or intermediate**
The bioactivity data is in the IC50 unit. Compounds having values of less than 1000 nM will be considered to be **active** while those greater than 10,000 nM will be considered to be **inactive**. As for those values in between 1,000 and 10,000 nM will be referred to as **intermediate**.

In [20]:
bioactivity_class = []
for i in df2.standard_value:
  if float(i) >= 10000:
    bioactivity_class.append("inactive")
  elif float(i) <= 1000:
    bioactivity_class.append("active")
  else:
    bioactivity_class.append("intermediate")

### **Iterate the *molecule_chembl_id* to a list**

In [21]:
mol_cid = []
for i in df2.molecule_chembl_id:
  mol_cid.append(i)

### **Iterate *canonical_smiles* to a list**

In [22]:
canonical_smiles = []
for i in df2.canonical_smiles:
  canonical_smiles.append(i)

### **Iterate *standard_value* to a list**

In [23]:
standard_value = []
for i in df2.standard_value:
  standard_value.append(i)

### **Combine the 4 lists into a dataframe**

In [24]:
data_tuples = list(zip(mol_cid, canonical_smiles, bioactivity_class, standard_value))
df3 = pd.DataFrame( data_tuples,  columns=['molecule_chembl_id', 'canonical_smiles', 'bioactivity_class', 'standard_value'])

In [25]:
df3

,molecule_chembl_id,canonical_smiles,bioactivity_class,standard_value
0,CHEMBL2402207,COc1ccc(S(=O)(=O)Nc2ccc(NS(=O)(=O)c3ccc(OC)cc3...,intermediate,2700.0
1,CHEMBL2402206,Cc1ccc(S(=O)(=O)c2cnc(SCC(=O)Nc3ccccc3C(F)(F)F...,inactive,118000.0
2,CHEMBL2402205,CC(C)C[C@H](NC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](...,active,33.0
3,CHEMBL2402207,COc1ccc(S(=O)(=O)Nc2ccc(NS(=O)(=O)c3ccc(OC)cc3...,intermediate,1700.0
4,CHEMBL3237245,COc1ccc(S(=O)(=O)N(CC(=O)O)c2ccc(N(CC(=O)O)S(=...,active,20.0
...,...,...,...,...
341,CHEMBL3237245,COc1ccc(S(=O)(=O)N(CC(=O)O)c2ccc(N(CC(=O)O)S(=...,active,7.7
342,CHEMBL2381968,O=C(O)[C@H]1CCCC[C@H]1C(=O)N1CCc2ccccc2[C@H]1C...,intermediate,1400.0
343,CHEMBL5272223,CC(=O)N[C@@H](CC(=O)O)C(=O)N1CSC[C@H]1C(=O)N[C...,active,31.0
344,CHEMBL1232461,CCNC(=O)C[C@@H]1N=C(c2ccc(Cl)cc2)c2cc(OC)ccc2-...,inactive,10000.0
345,CHEMBL6102564,NC(=O)CN(c1ccc(N(CC(N)=O)S(=O)(=O)c2ccc(N)cc2)...,active,230.0

### **Alternative method**

In [26]:
selection = ['molecule_chembl_id', 'canonical_smiles', 'standard_value']
df3 = df2[selection]
df3

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL2402207,COc1ccc(S(=O)(=O)Nc2ccc(NS(=O)(=O)c3ccc(OC)cc3...,2700.0
1,CHEMBL2402206,Cc1ccc(S(=O)(=O)c2cnc(SCC(=O)Nc3ccccc3C(F)(F)F...,118000.0
2,CHEMBL2402205,CC(C)C[C@H](NC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](...,33.0
3,CHEMBL2402207,COc1ccc(S(=O)(=O)Nc2ccc(NS(=O)(=O)c3ccc(OC)cc3...,1700.0
4,CHEMBL3237245,COc1ccc(S(=O)(=O)N(CC(=O)O)c2ccc(N(CC(=O)O)S(=...,20.0
...,...,...,...
378,CHEMBL3237245,COc1ccc(S(=O)(=O)N(CC(=O)O)c2ccc(N(CC(=O)O)S(=...,7.7
379,CHEMBL2381968,O=C(O)[C@H]1CCCC[C@H]1C(=O)N1CCc2ccccc2[C@H]1C...,1400.0
380,CHEMBL5272223,CC(=O)N[C@@H](CC(=O)O)C(=O)N1CSC[C@H]1C(=O)N[C...,31.0
381,CHEMBL1232461,CCNC(=O)C[C@@H]1N=C(c2ccc(Cl)cc2)c2cc(OC)ccc2-...,10000.0
382,CHEMBL6102564,NC(=O)CN(c1ccc(N(CC(N)=O)S(=O)(=O)c2ccc(N)cc2)...,230.0

In [27]:
pd.concat([df3,pd.Series(bioactivity_class)], axis=1)

,molecule_chembl_id,canonical_smiles,standard_value,0
0,CHEMBL2402207,COc1ccc(S(=O)(=O)Nc2ccc(NS(=O)(=O)c3ccc(OC)cc3...,2700.0,intermediate
1,CHEMBL2402206,Cc1ccc(S(=O)(=O)c2cnc(SCC(=O)Nc3ccccc3C(F)(F)F...,118000.0,inactive
2,CHEMBL2402205,CC(C)C[C@H](NC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](...,33.0,active
3,CHEMBL2402207,COc1ccc(S(=O)(=O)Nc2ccc(NS(=O)(=O)c3ccc(OC)cc3...,1700.0,intermediate
4,CHEMBL3237245,COc1ccc(S(=O)(=O)N(CC(=O)O)c2ccc(N(CC(=O)O)S(=...,20.0,active
...,...,...,...,...
195,NaN,NaN,NaN,inactive
196,NaN,NaN,NaN,intermediate
197,NaN,NaN,NaN,intermediate
198,NaN,NaN,NaN,intermediate
199,NaN,NaN,NaN,inactive

Saves dataframe to CSV file

In [28]:
df3.to_csv('bioactivity_preprocessed_data.csv', index=False)

In [29]:
! ls -l

total 376
-rw-r--r-- 1 root root 328475 Sep 14 10:48 bioactivity_data.csv
-rw-r--r-- 1 root root  46039 Sep 14 10:48 bioactivity_preprocessed_data.csv
drwxr-xr-x 1 root root   4096 Sep  4 13:25 sample_data

---