# **Computational Drug Discovery [Part 1] Download Bioactivity Data**

## **ChEMBL Database**

The [*ChEMBL Database*](https://www.ebi.ac.uk/chembl/) is a database that contains curated bioactivity data of more than 2 million compounds. It is compiled from more than 76,000 documents, 1.2 million assays and the data spans 13,000 targets and 1,800 cells and 33,000 indications.
[Data as of March 25, 2020; ChEMBL version 26].

## **Installing libraries**

Install the ChEMBL web service package so that we can retrieve bioactivity data from the ChEMBL Database.

In [45]:
! pip install chembl_webresource_client

Requirement already satisfied: chembl_webresource_client in /usr/local/lib/python3.13/dist-packages (0.10.9)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (2.32.4)
Requirement already satisfied: requests-cache~=1.2 in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (1.3.3)
Requirement already satisfied: easydict in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.19)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.7.22)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: cattrs>=22.2 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.2.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.11.7)
Requirement already satisfied: url-normalize>=2.0 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (3.0.0)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.13/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.16.0)

## **Importing libraries**

In [46]:
# Import necessary libraries
import pandas as pd
from chembl_webresource_client.new_client import new_client

## **Search for Target protein**

### **Target search for keap1**

In [47]:
# Target search for EGFR
target = new_client.target
target_query = target.search('EGFR')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,EGFR/PPP1CA,17.0,False,CHEMBL4523747,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
1,[],Homo sapiens,CCN2-EGFR,17.0,False,CHEMBL5465557,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
2,[],Mus musculus,Epidermal growth factor receptor,15.0,False,CHEMBL3608,"[{'accession': 'Q01279', 'component_descriptio...",SINGLE PROTEIN,10090
3,[],Mus musculus,Protein cereblon/Epidermal growth factor receptor,13.0,False,CHEMBL6193842,"[{'accession': 'Q01279', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,10090
4,[],Homo sapiens,Epidermal growth factor receptor,11.0,False,CHEMBL203,"[{'accession': 'P00533', 'component_descriptio...",SINGLE PROTEIN,9606
5,[],Homo sapiens,Protein cereblon/Epidermal growth factor receptor,11.0,False,CHEMBL4523680,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
6,[],Homo sapiens,Epidermal growth factor receptor,10.0,False,CHEMBL2363049,"[{'accession': 'P04626', 'component_descriptio...",PROTEIN FAMILY,9606
7,[],Homo sapiens,MER intracellular domain/EGFR extracellular do...,10.0,False,CHEMBL3137284,"[{'accession': 'P00533', 'component_descriptio...",CHIMERIC PROTEIN,9606
8,[],Homo sapiens,von Hippel-Lindau disease tumor suppressor/Epi...,10.0,False,CHEMBL4523998,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
9,[],Mus musculus,Protein cereblon/Epidermal growth factor receptor,10.0,False,CHEMBL6193841,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,10090
10,[],Homo sapiens,Receptor tyrosine-protein kinase erbB-2,9.0,False,CHEMBL1824,"[{'accession': 'P04626', 'component_descriptio...",SINGLE PROTEIN,9606
11,[],Rattus norvegicus,Receptor tyrosine-protein kinase erbB-2,9.0,False,CHEMBL3848,"[{'accession': 'P06494', 'component_descriptio...",SINGLE PROTEIN,10116
12,[],Homo sapiens,Receptor tyrosine-protein kinase erbB-4,9.0,False,CHEMBL3009,"[{'accession': 'Q15303', 'component_descriptio...",SINGLE PROTEIN,9606
13,[],Homo sapiens,Receptor tyrosine-protein kinase erbB-3,9.0,False,CHEMBL5838,"[{'accession': 'P21860', 'component_descriptio...",SINGLE PROTEIN,9606
14,[],Homo sapiens,Epidermal growth factor receptor and ErbB2 (HE...,9.0,False,CHEMBL2111431,"[{'accession': 'P04626', 'component_descriptio...",PROTEIN FAMILY,9606
15,[],Mus musculus,Receptor tyrosine-protein kinase erbB-2,9.0,False,CHEMBL2311234,"[{'accession': 'P70424', 'component_descriptio...",SINGLE PROTEIN,10090
16,[],Homo sapiens,FASN/HER2,9.0,False,CHEMBL4106134,"[{'accession': 'P04626', 'component_descriptio...",PROTEIN COMPLEX,9606
17,[],Homo sapiens,ErbB-2/ErbB-3 heterodimer,9.0,False,CHEMBL4630723,"[{'accession': 'P04626', 'component_descriptio...",PROTEIN COMPLEX,9606
18,[],Homo sapiens,Baculoviral IAP repeat-containing protein 2/Ep...,9.0,False,CHEMBL4802031,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
19,[],Homo sapiens,von Hippel-Lindau disease tumor suppressor/Rec...,9.0,False,CHEMBL5465227,"[{'accession': 'P04626', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
20,[],Homo sapiens,Microtubule-associated protein 1 light chain 3...,9.0,False,CHEMBL6066839,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
21,[],Homo sapiens,Glucose-induced degradation protein 4 homolog/...,9.0,False,CHEMBL6066845,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
22,[],Homo sapiens,E3 ubiquitin-protein ligase Mdm2/Epidermal gro...,9.0,False,CHEMBL6193792,"[{'accession': 'Q00987', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
23,[],Homo sapiens,UBR/Epidermal growth factor receptor,9.0,False,CHEMBL6193830,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
24,[],Homo sapiens,Protein zyg-11 homolog B/Protein zer-1 homolog...,9.0,False,CHEMBL6193837,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
25,[],Homo sapiens,E3 ubiquitin-protein ligase RNF149/Epidermal g...,9.0,False,CHEMBL6195769,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606

In [48]:
selected_target = targets.target_chembl_id[4]
selected_target

'CHEMBL203'

Here, we will retrieve only bioactivity data for *coronavirus 3C-like proteinase* (CHEMBL3927) that are reported as IC$_{50}$ values in nM (nanomolar) unit.

In [49]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [50]:
df = pd.DataFrame.from_dict(res)

In [51]:
df.head(3)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,32260,[],CHEMBL674637,Inhibitory activity towards tyrosine phosphory...,B,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,uM,UO_0000065,None,0.041
1,None,None,32263,[],CHEMBL621151,Inhibition of autophosphorylation of human epi...,F,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,uM,UO_0000065,None,0.3
2,None,None,32265,[],CHEMBL615325,Inhibition of ligand-induced proliferation in ...,F,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,uM,UO_0000065,None,7.82

In [52]:
df.standard_type.unique()

array(['IC50'], dtype=object)

Finally we will save the resulting bioactivity data to a CSV file **bioactivity_data.csv**.

In [53]:
df.to_csv('bioactivity_data.csv', index=False)

In [54]:
! head bioactivity_data.csv

action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,modality,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,,32260,[],CHEMBL674637,Inhibitory activity towards tyrosine phosphorylation for the epidermal growth factor-receptor kinase,B,,,BAO_0000190,BAO_0000357,single protein format,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)c32)[nH]1,,,CHEMBL1134862,Bioorg Med Chem Lett,2002.0,"{'bei': '19.25', 'le': '0.37', 'lle': '2.94', 'sei': '8.93'}",,CHEMBL68920,,CHEMBL68920,7.39,0,http://www.openphacts.org/units/Nanomolar,119482,=,1,1,=,,IC50,nM,,41.0,CHEMBL203,Homo sapiens,Epidermal growth factor receptor,9606,,,IC50,uM,UO_0000065,,0.041
,,32263,[],CHEMBL621151,Inhibition of autophosphorylation of human epidermal growth factor-receptor (EGF-R) expressed in A431 cells,F,,,BAO_0000190,BAO_0000219,cell-based format,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)c32)[nH]1,,,CHEMBL1134862,Bioorg Med Chem Lett,2002.0,,,CHEMBL68920,,CHEMBL68920,6.52,0,http://www.openphacts.org/units/Nanomolar,119482,=,1,1,=,,IC50,nM,,300.0,CHEMBL203,Homo sapiens,Epidermal growth factor receptor,9606,,,IC50,uM,UO_0000065,,0.3
,,32265,[],CHEMBL615325,Inhibition of ligand-induced proliferation in human EGF-R Kinase expressing 3T3 cells,F,,,BAO_0000190,BAO_0000219,cell-based format,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)c32)[nH]1,,,CHEMBL1134862,Bioorg Med Chem Lett,2002.0,,,CHEMBL68920,,CHEMBL68920,5.11,0,http://www.openphacts.org/units/Nanomolar,119482,=,1,1,=,,IC50,nM,,7820.0,CHEMBL203,Homo sapiens,Epidermal growth factor receptor,9606,,,IC50,uM,UO_0000065,,7.82
,,32267,[],CHEMBL674637,Inhibitory activity towards tyrosine phosphorylation for the epidermal growth factor-receptor kinase,B,,,BAO_0000190,BAO_0000357,single protein format,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(Nc3ccc(F)c(Cl)c3)c21,,,CHEMBL1134862,Bioorg Med Chem Lett,2002.0,"{'bei': '14.02', 'le': '0.27', 'lle': '3.16', 'sei': '6.03'}",,CHEMBL69960,,CHEMBL69960,6.77,0,http://www.openphacts.org/units/Nanomolar,119494,=,1,1,=,,IC50,nM,,170.0,CHEMBL203,Homo sapiens,Epidermal growth factor receptor,9606,,,IC50,uM,UO_0000065,,0.17
,,32270,[],CHEMBL621151,Inhibition of autophosphorylation of human epidermal growth factor-receptor (EGF-R) expressed in A431 cells,F,,,BAO_0000190,BAO_0000219,cell-based format,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(Nc3ccc(F)c(Cl)c3)c21,,,CHEMBL1134862,Bioorg Med Chem Lett,2002.0,,,CHEMBL69960,,CHEMBL69960,7.40,0,http://www.openphacts.org/units/Nanomolar,119494,=,1,1,=,,IC50,nM,,40.0,CHEMBL203,Homo sapiens,Epidermal growth factor receptor,9606,,,IC50,uM,UO_0000065,,0.04
,,32272,[],CHEMBL615325,Inhibition of ligand-induced proliferation in human EGF-R Kinase expressing 3T3 cells,F,,,BAO_0000190,BAO_0000219,cell-based format,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(Nc3ccc(F)c(Cl)c3)c21,,,CHEMBL1134862,Bioorg Med Chem Lett,2002.0,,,CHEMBL69960,,CHEMBL69960,6.36,0,http://www.openphacts.org/units/Nanomolar,119494,=,1,1,=,,IC50,nM,,440.0,CHEMBL203,Homo sapiens,Epidermal growth factor receptor,9606,,,IC50,uM,UO_0000065,,0.44
,,32680,[],CHEMBL677833,In vitro inhibition of Epidermal growth factor receptor tyrosine kinase isolated from A431 (human carcinoma).,B,,,BAO_0000190,BAO_0000357,single protein format,CN(c1ccccc1)c1ncnc2ccc(N/N=N/Cc3ccccn3)cc12,,,CHEMBL1145114,J Med Chem,2003.0,"{'bei': '13.62', 'le': '0.25', 'lle': '0.26', 'sei': '6.40'}",,CHEMBL137635,,CHEMBL137635,5.03,0,http://www.openphacts.org/units/Nanomolar,262238,=,1,1,=,,IC50,nM,,9300.0,CHEMBL203,Homo sapiens,Epidermal growth factor receptor,9606,,,IC50,uM,UO_0000065,,9.3
,,32770,[],CHEMBL674643,Inhibitory concentration of EGF dependent autophosphorylation of epidermal growth factor receptor kinase,B,,,BAO_0000190,BAO_0000357,single protein format,CC(=C(C#N)C#N)c1ccc(NC(=O)CCC(=O)O)cc1,Outside typical range,"Values for this activity type are unusually large/small, so may not be accurate",CHEMBL1124610,J Med Chem,1989.0,,,CHEMBL306988,,CHEMBL306988,,0,http://www.openphacts.org/units/Nanomolar,137177,=,1,1,=,,IC50,nM,,500000.0,CHEMBL203,Homo sapiens,Epidermal growth factor receptor,9606,,,IC50,uM,UO_0000065,,500.0
,,32772,[],CHEMBL674643,Inhibitory concentration of EGF dependent autophosphorylation of epidermal growth factor receptor kinase,B,,,BAO_0000190,BAO_0000357,single protein format,O=C(O)/C=C/c1ccc(O)cc1,Outside typical range,"Values for this activity type are unusually large/small, so may not be accurate",CHEMBL1124610,J Med Chem,1989.0,,,CHEMBL66879,COUMARIC ACID,CHEMBL66879,,0,http://www.openphacts.org/units/Nanomolar,137215,=,1,1,=,,IC50,nM,,3000000.0,CHEMBL203,Homo sapiens,Epidermal growth factor receptor,9606,,,IC50,uM,UO_0000065,,3000.0

## **Handling missing data**
If any compounds has missing value for the **standard_value** column then drop it

In [64]:
df2 = df[df.standard_value.notna()].reset_index(drop=True)
df2

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,32260,[],CHEMBL674637,Inhibitory activity towards tyrosine phosphory...,B,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,uM,UO_0000065,None,0.041
1,None,None,32263,[],CHEMBL621151,Inhibition of autophosphorylation of human epi...,F,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,uM,UO_0000065,None,0.3
2,None,None,32265,[],CHEMBL615325,Inhibition of ligand-induced proliferation in ...,F,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,uM,UO_0000065,None,7.82
3,None,None,32267,[],CHEMBL674637,Inhibitory activity towards tyrosine phosphory...,B,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,uM,UO_0000065,None,0.17
4,None,None,32270,[],CHEMBL621151,Inhibition of autophosphorylation of human epi...,F,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,uM,UO_0000065,None,0.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25194,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29313763,[],CHEMBL6184534,Inhibition of wildtype EGFR (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,nM,UO_0000065,None,9.8
25195,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29313764,[],CHEMBL6184534,Inhibition of wildtype EGFR (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,nM,UO_0000065,None,130.1
25196,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29313765,[],CHEMBL6184534,Inhibition of wildtype EGFR (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,nM,UO_0000065,None,4.81
25197,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29313767,[],CHEMBL6184534,Inhibition of wildtype EGFR (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,nM,UO_0000065,None,13.08
25198,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29313803,[],CHEMBL6184543,Inhibition of EGFR (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,nM,UO_0000065,None,0.025

Apparently, for this dataset there is no missing data. But we can use the above code cell for bioactivity data of other target protein.

## **Data pre-processing of the bioactivity data**

### **Labeling compounds as either being active, inactive or intermediate**
The bioactivity data is in the IC50 unit. Compounds having values of less than 1000 nM will be considered to be **active** while those greater than 10,000 nM will be considered to be **inactive**. As for those values in between 1,000 and 10,000 nM will be referred to as **intermediate**.

In [66]:
bioactivity_class = []
for i in df2.standard_value:
  if float(i) >= 10000:
    bioactivity_class.append("inactive")
  elif float(i) <= 1000:
    bioactivity_class.append("active")
  else:
    bioactivity_class.append("intermediate")

### **Iterate the *molecule_chembl_id* to a list**

In [67]:
mol_cid = []
for i in df2.molecule_chembl_id:
  mol_cid.append(i)

### **Iterate *canonical_smiles* to a list**

In [58]:
canonical_smiles = []
for i in df2.canonical_smiles:
  canonical_smiles.append(i)

### **Iterate *standard_value* to a list**

In [59]:
standard_value = []
for i in df2.standard_value:
  standard_value.append(i)

### **Combine the 4 lists into a dataframe**

In [68]:
data_tuples = list(zip(mol_cid, canonical_smiles, bioactivity_class, standard_value))
df3 = pd.DataFrame( data_tuples,  columns=['molecule_chembl_id', 'canonical_smiles', 'bioactivity_class', 'standard_value'])

In [69]:
df3

,molecule_chembl_id,canonical_smiles,bioactivity_class,standard_value
0,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,active,41.0
1,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,active,300.0
2,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,intermediate,7820.0
3,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,active,170.0
4,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,active,40.0
...,...,...,...,...
25194,CHEMBL6191667,O=C(CCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,active,9.8
25195,CHEMBL6192203,O=C(CCCCCOc1cc2ncnc(Nc3ccccc3Cl)c2c2c1OCCO2)NO,active,130.1
25196,CHEMBL6191199,O=C(CCCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,active,4.81
25197,CHEMBL939,COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1OCCCN1CCOCC1,active,13.08
25198,CHEMBL29197,COc1cc2ncnc(Nc3cccc(Br)c3)c2cc1OC,active,0.025

### **Alternative method**

In [70]:
selection = ['molecule_chembl_id', 'canonical_smiles', 'standard_value']
df3 = df2[selection]
df3

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,41.0
1,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,300.0
2,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,7820.0
3,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,170.0
4,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,40.0
...,...,...,...
25194,CHEMBL6191667,O=C(CCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,9.8
25195,CHEMBL6192203,O=C(CCCCCOc1cc2ncnc(Nc3ccccc3Cl)c2c2c1OCCO2)NO,130.1
25196,CHEMBL6191199,O=C(CCCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,4.81
25197,CHEMBL939,COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1OCCCN1CCOCC1,13.08
25198,CHEMBL29197,COc1cc2ncnc(Nc3cccc(Br)c3)c2cc1OC,0.025

In [71]:
pd.concat([df3,pd.Series(bioactivity_class)], axis=1)

,molecule_chembl_id,canonical_smiles,standard_value,0
0,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,41.0,active
1,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,300.0,active
2,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,7820.0,intermediate
3,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,170.0,active
4,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,40.0,active
...,...,...,...,...
25194,CHEMBL6191667,O=C(CCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,9.8,active
25195,CHEMBL6192203,O=C(CCCCCOc1cc2ncnc(Nc3ccccc3Cl)c2c2c1OCCO2)NO,130.1,active
25196,CHEMBL6191199,O=C(CCCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,4.81,active
25197,CHEMBL939,COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1OCCCN1CCOCC1,13.08,active
25198,CHEMBL29197,COc1cc2ncnc(Nc3cccc(Br)c3)c2cc1OC,0.025,active

Saves dataframe to CSV file

In [72]:
df3.to_csv('bioactivity_preprocessed_data.csv', index=False)

In [ ]:
! ls -l

total 380
-rw-r--r-- 1 root root 328475 Sep 13 17:11 bioactivity_data.csv
-rw-r--r-- 1 root root  46039 Sep 13 17:18 bioactivity_preprocessed_data.csv
drwx------ 5 root root   4096 Sep 13 17:12 gdrive
drwxr-xr-x 1 root root   4096 Sep  4 13:25 sample_data

Let's copy to the Google Drive

In [ ]:
! cp bioactivity_preprocessed_data.csv "/content/gdrive/My Drive/Colab Notebooks/EGFR"

In [ ]:
! ls "/content/gdrive/My Drive/Colab Notebooks/EGFR"

bioactivity_data.csv  bioactivity_preprocessed_data.csv

---