# **Bioinformatics Project - Computational Drug Discovery [Part 3] Descriptor Calculation and Dataset Preparation**

## **Download PaDEL-Descriptor**

In [ ]:
!pip install padelpy

## **Load bioactivity data**

Download the curated ChEMBL bioactivity data that has been pre-processed from Parts 1 and 2 of this Bioinformatics Project series. Here we will be using the **bioactivity_data_3class_pIC50.csv** file that essentially contain the pIC50 values that we will be using for building a regression model.

In [31]:
import pandas as pd

In [32]:
df3 = pd.read_csv('bioactivity_data_2class.csv')

In [33]:
df3

,molecule_chembl_id,canonical_smiles,MW,LogP,NumHDonors,NumHAcceptors,pIC50,bioactivity_class
0,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,383.814,4.45034,3.0,4.0,7.387216,active
1,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,383.814,4.45034,3.0,4.0,6.522879,active
2,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,482.903,3.61432,3.0,6.0,6.769551,active
3,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,482.903,3.61432,3.0,6.0,7.397940,active
4,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,482.903,3.61432,3.0,6.0,6.356547,active
...,...,...,...,...,...,...,...,...
22037,CHEMBL6191667,O=C(CCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,NaN,NaN,NaN,NaN,8.008774,active
22038,CHEMBL6192203,O=C(CCCCCOc1cc2ncnc(Nc3ccccc3Cl)c2c2c1OCCO2)NO,NaN,NaN,NaN,NaN,6.885723,active
22039,CHEMBL6191199,O=C(CCCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,NaN,NaN,NaN,NaN,8.317855,active
22040,CHEMBL939,COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1OCCCN1CCOCC1,NaN,NaN,NaN,NaN,7.883392,active
22041,CHEMBL29197,COc1cc2ncnc(Nc3cccc(Br)c3)c2cc1OC,NaN,NaN,NaN,NaN,10.602060,active

In [34]:
selection = ['canonical_smiles','molecule_chembl_id']
df3_selection = df3[selection]
df3_selection.to_csv('molecule.smi', sep='\t', index=False, header=False)

In [35]:
! cat molecule.smi | head -5

Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)c32)[nH]1	CHEMBL68920
Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)c32)[nH]1	CHEMBL68920
Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(Nc3ccc(F)c(Cl)c3)c21	CHEMBL69960
Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(Nc3ccc(F)c(Cl)c3)c21	CHEMBL69960
Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(Nc3ccc(F)c(Cl)c3)c21	CHEMBL69960

In [36]:
! cat molecule.smi | wc -l

22042

## **Calculate fingerprint descriptors**

In [37]:
%%writefile padel.sh
java -Xms512m -Xmx512m -jar PaDEL-Descriptor/PaDEL-Descriptor.jar -removesalt -retained3d-descriptors -file descriptors_output.csv -dir ./ -fingerprints

Overwriting padel.sh

### **Calculate PaDEL descriptors**

In [38]:
! cat padel.sh

java -Xms512m -Xmx512m -jar PaDEL-Descriptor/PaDEL-Descriptor.jar -removesalt -retained3d-descriptors -file descriptors_output.csv -dir ./ -fingerprints

In [39]:
! ls -l

total 12476
-rw-r--r-- 1 root root 3093686 Sep 14 08:49 bioactivity_data_2class.csv
-rw-r--r-- 1 root root 8023237 Sep 14 08:44 descriptors_output.csv
-rw-r--r-- 1 root root 1643710 Sep 14 08:49 molecule.smi
-rw-r--r-- 1 root root     153 Sep 14 08:49 padel.sh
drwxr-xr-x 1 root root    4096 Sep  4 13:25 sample_data

## **Preparing the X and Y Data Matrices**

### **X data matrix**

In [40]:
df3_X = pd.read_csv('descriptors_output.csv')

In [ ]:
from padelpy import padeldescriptor

padeldescriptor(
    mol_dir='molecule.smi',
    d_file='descriptors_output.csv',
    fingerprints=True,
    removesalt=True
)

In [42]:
df3_X

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL68920,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL68920,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CHEMBL69960,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL69960,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL69960,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4504,CHEMBL1829273,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4505,CHEMBL1829274,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4506,CHEMBL1829275,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4507,CHEMBL1173718,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4508,CHEMBL1834657,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [46]:
df3_X = df3_X.drop(columns=['Name'])
df3_X

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4504,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4505,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4506,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4507,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4508,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

## **Y variable**

### **Convert IC50 to pIC50**

In [47]:
df3_Y = df3['pIC50']
df3_Y

0         7.387216
1         6.522879
2         6.769551
3         7.397940
4         6.356547
           ...
22037     8.008774
22038     6.885723
22039     8.317855
22040     7.883392
22041    10.602060
Name: pIC50, Length: 22042, dtype: float64

## **Combining X and Y variable**

In [48]:
# Align both DataFrames to the shortest matching length and reset indices
min_len = min(len(df3_X), len(df3_Y))

df3_X_clean = df3_X.iloc[:min_len].reset_index(drop=True)
df3_Y_clean = df3_Y.iloc[:min_len].reset_index(drop=True)

# Combine X and Y variables safely
dataset3 = pd.concat([df3_X_clean, df3_Y_clean], axis=1)

In [49]:
print("Total NaN values:", dataset3.isnull().sum().sum())
print("Final Dataset Shape:", dataset3.shape)

Total NaN values: 0
Final Dataset Shape: (4509, 882)

In [51]:
dataset3.to_csv('GFRE_bioactivity_data_3class_pIC50_pubchem_fp.csv', index=False)

# **Let's download the CSV file to your local computer for the Part 3B (Model Building).**